# Generated by Django 3.2.4 on 2021-06-25 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitiosApp', '0004_solicitudayuda'),
    ]

    operations = [
        migrations.CreateModel(
            name='recepciontrabajo',
            fields=[
                ('num_unico', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.CharField(max_length=30)),
                ('tipo_de_trabajo', models.CharField(max_length=100)),
                ('comentarios', models.CharField(max_length=50)),
                ('materiales', models.CharField(max_length=200)),
                ('solicitudt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitiosApp.solicitudtrabajo')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitiosApp.categoriautrabajador')),
            ],
        ),
    ]
