# Generated by Django 3.2 on 2021-06-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitiosApp', '0005_recepciontrabajo'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('num_unico', models.IntegerField(primary_key=True, serialize=False)),
                ('trabajo_cate', models.CharField(max_length=150)),
            ],
        ),
    ]
