# Generated by Django 3.2 on 2021-06-25 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitiosApp', '0006_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepciontrabajo',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sitiosApp.categoria'),
            preserve_default=False,
        ),
    ]
