# Generated by Django 3.2 on 2021-06-27 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitiosApp', '0007_recepciontrabajo_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudtrabajo',
            name='publicar',
            field=models.BooleanField(default=False),
        ),
    ]
