# Generated by Django 3.2 on 2021-06-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitiosApp', '0008_solicitudtrabajo_publicar'),
    ]

    operations = [
        migrations.CreateModel(
            name='perfilusuario',
            fields=[
                ('nombre_perf', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('imagen', models.ImageField(null=True, upload_to='imgperfil')),
            ],
        ),
    ]
