# Generated by Django 3.2 on 2021-06-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitiosApp', '0009_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaunormal',
            name='descripcion',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
