# Generated by Django 3.2 on 2021-06-28 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitiosApp', '0010_categoriaunormal_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudtrabajo',
            name='comentario',
            field=models.TextField(default='--'),
        ),
    ]
