# Generated by Django 3.2 on 2021-06-28 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitiosApp', '0011_solicitudtrabajo_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudayuda',
            name='comentario',
            field=models.TextField(default='--'),
        ),
        migrations.AddField(
            model_name='solicitudayuda',
            name='revisado',
            field=models.BooleanField(default=False),
        ),
    ]
